---
title: "Global_Terrorism_Data_Analysis_And_Visualization"
author: "Pooja, Rajesh, Navya"
date: "2025-02-27"
output: html_document
---

#ROLE 1: Navya - Data wrangling
#ROLE 2: Pooja - Data Analysis 
#ROLE 3: Rajesh - Data Visualization

```{r}
# Data Wrangling
# Import the dataset
terrorism_data<-read.csv("globalterrorismdb_0718dist.csv")
```

```{r}
#View the first few rows
print.data.frame(terrorism_data)
#Exploring the data structure
str(terrorism_data)
#View the statistical summary of the data
summary(terrorism_data)
```

### Observations: As per the task for group 4, it is observed that there are no missing values for the target type1 column.
```{r}
#Data Analysis
#Load the tidyverse package
library(tidyverse)
terrorism_data_ordered <- terrorism_data %>% 
  select(targtype1, targtype1_txt) %>% 
  arrange(targtype1)
```

```{r}
#View the first few rows
print.data.frame(terrorism_data_ordered)
#View number of rows
nrow(terrorism_data_ordered)
#View number of cols
ncol(terrorism_data_ordered)
```
```{r}
#Role 2 Analysis Questions: Count the number of attacks on each target type
# Load dplyr
library(dplyr)

# Group by count using dplyr
number_of_attack_per_target_type <- terrorism_data_ordered %>% group_by(targtype1_txt) %>% 
  summarise(total_count=n(),
            .groups = 'drop')
print.data.frame(number_of_attack_per_target_type)
```
```{r}
#Role 3 - Data Visualization - Bar plot of attacks per target type

# Load ggplot2 
library(ggplot2)

# Create the bar plot
ggplot(number_of_attack_per_target_type, aes(x = reorder(targtype1_txt, total_count), y = total_count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  labs(
    title = "Number of Attacks on Each Target Type",
    x = "Target Type",
    y = "Number of Attacks"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # Rotate x-axis labels for better readability

```

